### ISSUE TITLE
Use the new Orchestrator logo

### ISSUE THREAD

**Issue by wouter1975** [workfloworchestrator/orchestrator-ui#599] opened 2023-12-20 10:26 UTC
- [ ] Use the new orchestrator logo
- [ ] Use the new color for the top bar (dark blue)
- [ ] Use the orchestrator favicon

Apply the changes to the opensource and surf specific app.

Information of the logo can be found at XXXX

**Comment by DutchBen** [comment] 2024-01-02 12:28
I think this is a duplicate of #578

**Closed** 2024-01-11 09:32 UTC
Labels: _R2
